add-bookings
Asteises/java-shareit pull request #1
Opened 2022-10-03 20:28 UTC by Asteises

2022-10-04 09:56 UTC, alexache requested changes

2022-10-04 09:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    @ResponseStatus(HttpStatus.OK)
По дефолту это и так будет овтет 200, стоит ли это прописывать?

2022-10-04 09:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +
Лучше поменьше пустых строк между полями

2022-10-04 09:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/services/UserServiceImpl.java
> +        if (user.getEmail() == null || user.getEmail().isEmpty() || !user.getEmail().contains("@")) {
Можно сделать это проверку первым делом, даже до конвертации ДТО -> model

2022-10-04 09:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/services/UserServiceImpl.java
> +        return UserMapper.toUserDto(user);
Мне кажется или в этом методе не вызывается userStorage?

2022-10-04 09:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/services/UserServiceImpl.java
> +    public User checkUser(long userId) throws UserNotFound {
Весь метод может быть заменен на 
`return userStorage.findById(userId).orElseThrow(() -> new UserNotFound(String.format("User by ID: %s - not found", userId));`

2022-10-04 09:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +    public ItemResponseDto findItemById(long itemId,
Метод, который в качестве аргументов получает сервисы, выглядит некоторым нарушением использования Dependency Injection, как минимум. Первый вопрос будет - почему не выставлять эти сервисы в качестве зависимостей данного сервиса? Второй - зависимость сервиса от других сервисов не очень хорошо., лучше использовать репозитории вместо этого

2022-10-04 09:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +            return ItemMapper.toItemResponseDto(item, lastBooking, nextBooking, commentService);
Тем более плохо добавлять сервис в качестве аргумента в маппер, создает очень много лишних зависимостей, Такой код будет очень тяжело тестировать и поддерживать. Почему бы вместо этого не получить комментарии через репозиторий и просто не передать их лист в маппер?

2022-10-04 09:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/comment/CommentServiceImpl.java
> +public class CommentServiceImpl implements CommentService {
Отдельный сервис для комментариев не нужен, это может быть частью ItemService

2022-10-04 09:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/comment/CommentServiceImpl.java
> +            if (bookings.stream().anyMatch(booking ->
Такие условия лучше делать частью SQL запроса, а не на уровне джавы

2022-10-04 09:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/comment/CommentServiceImpl.java
> +            throw new BadRequestException("ыыыы");
Текст ошибки лучше сделать немного информативнее :)

2022-10-04 09:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                Optional<Booking> optionalBooking = bookingRepository.findByItemAndBooker(currentItem, booker);
Не очень понял для чего этот запрос? Чтобы избежать дублирования бронирования? Но тогда не очень очевидно почему просто ошибку не возвращать

2022-10-04 09:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                            BookingStatus.WAITING.name(),
Мне кажется можно оставлять енамы как есть, и JPA разберется с конвертацией в строку

2022-10-04 09:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +
Потерян @Override

2022-10-04 09:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    @Override
Эти методы не несут смысловой нагрузки, это как раз "+" к тому, что другие сервисы и сами могут работать напрямую с репозиторием

2022-10-04 14:31 UTC, Asteises commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    @ResponseStatus(HttpStatus.OK)
Уже прописал, не убирать же =)

2022-10-04 14:32 UTC, Asteises commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +
Исправил.

2022-10-04 14:33 UTC, Asteises commented on src/main/java/ru/practicum/shareit/user/services/UserServiceImpl.java
> +        if (user.getEmail() == null || user.getEmail().isEmpty() || !user.getEmail().contains("@")) {
Исправил.

2022-10-04 14:34 UTC, Asteises commented on src/main/java/ru/practicum/shareit/user/services/UserServiceImpl.java
> +        return UserMapper.toUserDto(user);
Исправил.

2022-10-04 14:38 UTC, Asteises commented on src/main/java/ru/practicum/shareit/user/services/UserServiceImpl.java
> +    public User checkUser(long userId) throws UserNotFound {
Исправил.

2022-10-05 08:18 UTC, Asteises commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +    public ItemResponseDto findItemById(long itemId,
Исправил.

2022-10-05 08:18 UTC, Asteises commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +            return ItemMapper.toItemResponseDto(item, lastBooking, nextBooking, commentService);
Исправил.

2022-10-05 08:26 UTC, Asteises commented on src/main/java/ru/practicum/shareit/item/comment/CommentServiceImpl.java
> +public class CommentServiceImpl implements CommentService {
Исправил.

2022-10-05 09:00 UTC, Asteises commented on src/main/java/ru/practicum/shareit/item/comment/CommentServiceImpl.java
> +            if (bookings.stream().anyMatch(booking ->
Я пробовал, но не выходит и не могу понят в чем проблема:

    @Query(value = "select * from BOOKINGS B " +
            "where (B.ITEM_ID = ?1 " +
            "and B.BOOKER_ID = ?2)" +
            "and (B.STATUS = ?3 or B.STATUS = ?4)" +
            "and B.START_DATE < ?4",
            nativeQuery = true)
    List<Booking> findAllByBooker_IdAndItem_IdAndStatusApprovedOrderByStartDesc(
            long itemId, long bookerId, String status1, String status2, LocalDateTime now);

2022-10-05 09:00 UTC, Asteises commented on src/main/java/ru/practicum/shareit/item/comment/CommentServiceImpl.java
> +            throw new BadRequestException("ыыыы");
Исправил.

2022-10-05 09:11 UTC, Asteises commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                Optional<Booking> optionalBooking = bookingRepository.findByItemAndBooker(currentItem, booker);
Я не могу понять как сделать по другому. Пробовал, но тесты не проходят. По тестам - пользователь может отправить запрос на бронирование еще раз, но мы не должны выбрасывать ошибку, а должны просто изменить бронирование которое уже есть. Я так понял.

2022-10-05 09:13 UTC, Asteises commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                            BookingStatus.WAITING.name(),
Возможно. Не хочется переписывать столько кода, чтобы проверить. В следующей ветке проверю эту теорию =)

2022-10-05 09:14 UTC, Asteises commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +
Исправил.

2022-10-05 09:17 UTC, Asteises commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    @Override
Исправил.

2022-10-05 19:43 UTC, alexache approved these changes

2022-10-06 14:26 UTC, merged