Add item requests
Asteises/java-shareit pull request #2
Opened 2022-10-23 17:07 UTC by Asteises

2022-10-24 21:26 UTC, alexache requested changes

2022-10-24 21:26 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                if (from != 0) {
Для чего это?

2022-10-24 21:26 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (from == null && size == null) {
Разве это возможно с дефольтными значениями страниц от контроллера?

2022-10-24 21:26 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/model/dto/RequestWithResponseDto.java
> +    List<ItemForRequestDto> items;
Не хватает модификатора доступа

2022-10-24 21:26 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +    List<RequestWithResponseDto> getRequestWithResponseDto(List<ItemRequest> itemRequests) {
Не хватает модификатора доступа

2022-10-24 21:26 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +    public ItemRequest checkItemRequest(long itemRequestId) throws NotFoundException {
Для чего этот метод в интерфейсе?

2022-10-24 21:26 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    public boolean equals(Object o) {
У ломбокаа есть аннотации на добавление таких методов

2022-10-24 21:26 UTC, alexache commented on src/test/java/ru/practicum/shareit/UserTest/UserServiceTest.java
> +    void findUserByIdTest() {
Направление верное, но тестов мало

2022-10-29 13:37 UTC, Asteises commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                if (from != 0) {
Так смог пройти 1 тест...

2022-10-29 13:39 UTC, Asteises commented on src/main/java/ru/practicum/shareit/request/model/dto/RequestWithResponseDto.java
> +    List<ItemForRequestDto> items;
исправил

2022-10-29 13:40 UTC, Asteises commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +    List<RequestWithResponseDto> getRequestWithResponseDto(List<ItemRequest> itemRequests) {
исправил

2022-10-29 13:40 UTC, Asteises commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +    public ItemRequest checkItemRequest(long itemRequestId) throws NotFoundException {
хм... наверное незачем, но я уже написал на него даже тесты =)

2022-10-29 13:42 UTC, Asteises commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    public boolean equals(Object o) {
исправил

2022-10-29 13:42 UTC, Asteises commented on src/test/java/ru/practicum/shareit/UserTest/UserServiceTest.java
> +    void findUserByIdTest() {
исправил

2022-10-29 13:43 UTC, Asteises commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (from == null && size == null) {
наверное уже не нужно

2022-10-30 09:55 UTC, alexache approved these changes

2022-10-30 15:59 UTC, Asteises commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                if (from != 0) {
Bookings get all with from = 2 & size = 2 when all=3

Вот этот тест. Мы должны вывести данные со второй страницы. Но по факту страницы считаются с 0 и эта вторая страница по сути третья. И на ней ничего нет.

2022-10-30 15:59 UTC, merged