Add docker
Asteises/java-shareit pull request #3
Opened 2022-11-02 15:26 UTC by Asteises

2022-11-04 20:44 UTC, alexache requested changes

2022-11-04 20:44 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        Map<String, Object> parameters = Map.of("approved", approved);
Мапа из одного элемента - это немного перебор, можно просто сформировать строку сразу

2022-11-04 20:44 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                @RequestParam boolean approved) {
И тут бы логгировать

2022-11-04 20:44 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<Object> updateItem(@RequestBody ItemDto itemDto,
Еще @Valid?

2022-11-04 20:44 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                              @RequestBody @Validated CommentDto commentDto) {
Может @Valid достаточно?

2022-11-04 20:44 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<Object> updateUser(@RequestBody UserDto userDto, @PathVariable long userId) {
@Valid?

2022-11-04 20:44 UTC, alexache commented on server/src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +
К сожалению гитхаб не дает добавить коммент к файлу без изщменения. В BookingServiceImpl  надо вынести проверки в гейтвей -   
```
public static Boolean checkPaging(Integer from, Integer size) throws BadRequestException {
        if (from == null && size == null) {
            return false;
        }
        if (size == 0) {
            throw new BadRequestException("size == 0");
        }
        return true;
    }

    public static boolean validateDates(LocalDateTime start, LocalDateTime end) {
        try {
            LocalDateTime current = LocalDateTime.now();
            return (start.isEqual(current) || start.isAfter(current)) && end.isAfter(start) && end.isAfter(current);
        } catch (DateTimeParseException ex) {
            ex.printStackTrace();
        }
        return false;
    }
```

2022-11-04 20:44 UTC, alexache commented on server/src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +            @RequestParam(required = false, defaultValue = "0") Integer from,
```
public static Boolean checkPaging(Integer from, Integer size) throws BadRequestException {
        if (from == null && size == null) {
            return false;
        }
        if (size == 0) {
            throw new BadRequestException("size == 0");
        }
        return true;
    }
```
из ItemServiceImpl тоже валидация для гейтвея

2022-11-05 07:57 UTC, Asteises commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        Map<String, Object> parameters = Map.of("approved", approved);
Исправил

2022-11-05 08:07 UTC, Asteises commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                @RequestParam boolean approved) {
Исправил

2022-11-05 08:11 UTC, Asteises commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<Object> updateItem(@RequestBody ItemDto itemDto,
Тут я не знал как лучше сделать, потому что в тестах в методе patch может прийти дто без основных полей. По этому в методах patch не стал делать валидацию. Фактически тут она происходит в сервисе в формате бизнес-логики.

2022-11-05 08:12 UTC, Asteises commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                              @RequestBody @Validated CommentDto commentDto) {
Исправил

2022-11-05 08:13 UTC, Asteises commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<Object> updateUser(@RequestBody UserDto userDto, @PathVariable long userId) {
тут тоже самое... метод patch в нем дто не валидируем

2022-11-05 12:33 UTC, Asteises commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        Map<String, Object> parameters = Map.of("approved", approved);
Исправить не получилось, с другими методами тесты валяться...

2022-11-05 12:34 UTC, Asteises commented on server/src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +
Исправил

2022-11-05 12:37 UTC, Asteises commented on server/src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +            @RequestParam(required = false, defaultValue = "0") Integer from,
Исправил

2022-11-06 06:34 UTC, alexache approved these changes

2022-11-06 06:34 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                              @RequestBody @Validated CommentDto commentDto) {
Не вижу изменения :)

2022-11-06 09:11 UTC, Asteises commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                              @RequestBody @Validated CommentDto commentDto) {
Точно. Я пару раз откатывал обратно проект. И забыл видимо. Переделаю уже в мейн ветке.

2022-11-06 09:11 UTC, merged